name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js dependencies
        run: |
          pnpm i

      - name: Build
        run: |
          pnpm build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tencent-ace-tools
          path: |
            src-tauri/target/release/bundle/**/*
